### ISSUE TITLE
num_nodes as batch_size

### ISSUE THREAD

**Issue by ghost** [Aveek-Saha/Graph-Attention-Net#1]
I tried my code with a large number of nodes (6004 nodes) in my dataset. I found that Keras don't assign batch_size bigger than 4803
https://github.com/Aveek-Saha/Graph-Attention-Net/blob/7dbbd2f6934642f7af3c5a07455dcc1d87ce01cd/train.py#L157

Here is the error: 

```
Graph info:  Name: 
Type: Graph
Number of nodes: 6004
Number of edges: 8815696
Average degree: 2936.6076
Model: "graph_attention"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            [(None, 768)]        0                                            
__________________________________________________________________________________________________
dropout (Dropout)               (None, 768)          0           input_1[0][0]                    
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 6004)]       0                                            
__________________________________________________________________________________________________
graph_attention_layer (GraphAtt (None, 64)           49280       dropout[0][0]                    
                                                                 input_2[0][0]                    
__________________________________________________________________________________________________
dropout_1 (Dropout)             (None, 64)           0           graph_attention_layer[0][0]      
__________________________________________________________________________________________________
graph_attention_layer_1 (GraphA (None, 21)           1386        dropout_1[0][0]                  
                                                                 input_2[0][0]                    
==================================================================================================
Total params: 50,666
Trainable params: 50,666
Non-trainable params: 0
__________________________________________________________________________________________________
None
Epoch 1/200
Traceback (most recent call last):
  File "/home/hzahera/Downloads/SVN/Graph-Attention-Net/train.py", line 91, in <module>
    model.fit([features, A],
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/hzahera/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [6004,768] vs. [4803,768]
         [[node graph_attention/dropout/dropout/Mul_1 (defined at /Downloads/SVN/Graph-Attention-Net/train.py:91) ]] [Op:__inference_train_function_22982]

Function call stack:
train_function
```

Any hint can help in this?

**Comment by ghost** [comment]
I fixed it, the error was due to validation_split=0.2. It requires to specify an explicit validation data.
